# => inherits: generic <= #


dhcpd:

  iface: eth0

  ddns_update_style: standard
  log_facility: local7

  domain_name: ea.local

  subnets:
    - bootp_support: true
      max_lease_time: 7200
      default_lease_time: 600
      address: 10.20.0.0
      netmask: 255.255.0.0
      broadcast_address: 10.20.255.255
      known_clients:
        start_address: 10.20.1.1
        end_address:   10.20.1.254
      unknown_clients:
        start_address: 10.20.0.1
        end_address:   10.20.0.254
      dns_servers:
        - 10.20.254.254
      ntp_servers:
        - 10.20.254.254
      routers:
        - 10.20.254.254

  hosts: []
    #- mac_address:
    #  address: 10.20.254.254
    #  hostname: eru

features:
  - openrc


# vim: set filetype=eruby.yaml :
